<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AssemblyName>RestoreCenter</AssemblyName>
    <RootNamespace>DPop.RestoreCenter</RootNamespace>
    <Version>0.4.17</Version>
    <FileVersion>0.4.17.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DPop.Common\DPop.Common.csproj" />
  </ItemGroup>
</Project>
