<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SimpleUpdate</AssemblyName>
    <RootNamespace>DPopCleaner.SimpleUpdate</RootNamespace>
    <ApplicationIcon>../../../dpopcleaner.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
