<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DiskAnalyzer</AssemblyName>
    <RootNamespace>DPop.DiskAnalyzer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DPop.Common\DPop.Common.csproj" />
  </ItemGroup>
</Project>
