[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$RootPath,
    [string]$OutputDir='_release/0.4.17/evidence/rev19-zapret-cleanup'
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;Add-Type -AssemblyName System.Drawing
$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$RootPath=if([IO.Path]::IsPathRooted($RootPath)){$RootPath}else{Join-Path $repoRoot $RootPath};$RootPath=[IO.Path]::GetFullPath($RootPath)
$OutputDir=if([IO.Path]::IsPathRooted($OutputDir)){$OutputDir}else{Join-Path $repoRoot $OutputDir};$OutputDir=[IO.Path]::GetFullPath($OutputDir);New-Item -ItemType Directory -Path $OutputDir -Force|Out-Null
$launcherPath=Join-Path $RootPath 'DPopCleaner.exe';$corePath=Join-Path $RootPath 'DPopCleaner.Core.exe'
$native=@'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;
public sealed class R19ODItem { public long Hwnd,Parent; public int Id,Pid,Left,Top,Right,Bottom; public bool Visible; public string Text; }
public static class R19ODNative {
 delegate bool EnumProc(IntPtr h,IntPtr x);[StructLayout(LayoutKind.Sequential)] struct RECT{public int L,T,R,B;}
 [StructLayout(LayoutKind.Sequential)] struct DRAWITEMSTRUCT{public uint CtlType,CtlID,itemID,itemAction,itemState;public IntPtr hwndItem,hDC;public RECT rcItem;public UIntPtr itemData;}
 [DllImport("user32.dll")] static extern bool EnumChildWindows(IntPtr p,EnumProc cb,IntPtr x);[DllImport("user32.dll")] static extern int GetDlgCtrlID(IntPtr h);[DllImport("user32.dll")] static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll")] static extern IntPtr GetParent(IntPtr h);[DllImport("user32.dll")] static extern bool GetWindowRect(IntPtr h,out RECT r);[DllImport("user32.dll")] static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);[DllImport("user32.dll",CharSet=CharSet.Unicode)] static extern int GetWindowText(IntPtr h,StringBuilder b,int n);[DllImport("user32.dll")] public static extern IntPtr SendMessage(IntPtr h,uint m,IntPtr w,IntPtr l);[DllImport("user32.dll")] public static extern bool SetWindowPos(IntPtr h,IntPtr a,int x,int y,int w,int z,uint f);
 static string Text(IntPtr h){var b=new StringBuilder(512);GetWindowText(h,b,b.Capacity);return b.ToString();}
 public static R19ODItem[] Probe(IntPtr root,int id){var a=new List<R19ODItem>();EnumProc cb=delegate(IntPtr h,IntPtr _){if(GetDlgCtrlID(h)!=id)return true;RECT r;GetWindowRect(h,out r);uint p;GetWindowThreadProcessId(h,out p);a.Add(new R19ODItem{Hwnd=h.ToInt64(),Parent=GetParent(h).ToInt64(),Id=id,Pid=(int)p,Visible=IsWindowVisible(h),Text=Text(h),Left=r.L,Top=r.T,Right=r.R,Bottom=r.B});return true;};EnumChildWindows(root,cb,IntPtr.Zero);GC.KeepAlive(cb);return a.ToArray();}
 public static long SyntheticDraw(IntPtr host,IntPtr button,int id,IntPtr hdc,int width,int height){var d=new DRAWITEMSTRUCT{CtlType=4,CtlID=(uint)id,itemID=0,itemAction=1,itemState=0,hwndItem=button,hDC=hdc,rcItem=new RECT{L=0,T=0,R=width,B=height},itemData=UIntPtr.Zero};var p=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(DRAWITEMSTRUCT)));try{Marshal.StructureToPtr(d,p,false);return SendMessage(host,0x002B,new IntPtr(id),p).ToInt64();}finally{Marshal.FreeHGlobal(p);}}
}
'@
Add-Type -TypeDefinition $native -Language CSharp
function Wait-Until([int]$Seconds,[string]$What,[scriptblock]$Condition){$d=[DateTime]::UtcNow.AddSeconds($Seconds);do{if(&$Condition){return};Start-Sleep -Milliseconds 120}while([DateTime]::UtcNow-lt$d);throw "Timed out waiting for $What"}
function Get-Core{foreach($p in @(Get-Process -Name 'DPopCleaner.Core' -ErrorAction SilentlyContinue)){try{if($p.Path-and[IO.Path]::GetFullPath($p.Path).Equals([IO.Path]::GetFullPath($corePath),[StringComparison]::OrdinalIgnoreCase)-and$p.MainWindowHandle-ne[IntPtr]::Zero){return$p}}catch{}};$null}
function Capture-Synthetic($sample,[string]$path){$w=[Math]::Max(1,$sample.Right-$sample.Left);$h=[Math]::Max(1,$sample.Bottom-$sample.Top);$bmp=[Drawing.Bitmap]::new($w,$h);$g=[Drawing.Graphics]::FromImage($bmp);$dc=$g.GetHdc();try{$result=[R19ODNative]::SyntheticDraw([IntPtr]$sample.Parent,[IntPtr]$sample.Hwnd,$sample.Id,$dc,$w,$h)}finally{$g.ReleaseHdc($dc);$g.Dispose()};try{$bmp.Save($path,[Drawing.Imaging.ImageFormat]::Png)}finally{$bmp.Dispose()};$result}
$launcher=$null;$core=$null
try{$settings=Join-Path $OutputDir 'rev19-ownerdraw-settings.ini';@('auto_update=0','tray_icon=0')|Set-Content $settings -Encoding ascii;$launcher=Start-Process $launcherPath -ArgumentList @('--no-update-check','--settings-path',('"'+$settings+'"')) -WorkingDirectory $RootPath -PassThru;Wait-Until 18 'core'{$script:core=Get-Core;$null-ne$script:core};$core=$script:core;$window=$core.MainWindowHandle;$tab=@([R19ODNative]::Probe($window,905))|Where-Object{$_.Visible}|Select-Object -First 1;if(-not$tab){throw 'Zapret tab missing'};[void][R19ODNative]::SendMessage([IntPtr]$tab.Hwnd,0x00F5,[IntPtr]::Zero,[IntPtr]::Zero);Wait-Until 8 'bridge proxy'{$null-ne(@([R19ODNative]::Probe($window,1702))|Where-Object{$_.Visible-and$_.Pid-eq$launcher.Id}|Select-Object -First 1)};[void][R19ODNative]::SetWindowPos($window,[IntPtr]::Zero,0,0,1908,950,0x0002-bor0x0004-bor0x0010-bor0x0400);Start-Sleep -Milliseconds 1200;$report=@();foreach($id in @(1701,1702,1713,1720)){$s=@([R19ODNative]::Probe($window,$id))|Where-Object{$_.Visible-and$_.Pid-eq$launcher.Id}|Select-Object -First 1;if(-not$s){throw "proxy $id missing"};$result=Capture-Synthetic $s (Join-Path $OutputDir ("rev19-synthetic-draw-{0}.png"-f$id));$report+=[pscustomobject]@{id=$id;text=$s.Text;hwnd=('0x{0:X}'-f$s.Hwnd);parent=('0x{0:X}'-f$s.Parent);send_result=$result};Write-Host "REV19_SYNTHETIC_DRAW id=$id text='$($s.Text)' result=$result"};$report|ConvertTo-Json|Set-Content (Join-Path $OutputDir 'rev19-ownerdraw-probe.json') -Encoding utf8;Write-Host 'REV19_OWNERDRAW_PROBE_OK'}finally{foreach($n in @('DPopCleaner','DPopCleaner.Core','SimpleUpdate')){foreach($p in @(Get-Process -Name $n -ErrorAction SilentlyContinue)){try{if($p.Path-and[IO.Path]::GetFullPath($p.Path).StartsWith($RootPath,[StringComparison]::OrdinalIgnoreCase)){Stop-Process $p.Id -Force -ErrorAction SilentlyContinue}}catch{}}}}
